# Generated by Django 6.0.2 on 2026-02-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='category',
            field=models.CharField(choices=[('Pushing', 'Push'), ('Pulling', 'Pull'), ('Legs', 'Legs'), ('Core', 'Core')], max_length=20),
        ),
    ]
