# Generated by Django 6.0.2 on 2026-02-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscles', '0002_alter_muscle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='category',
            field=models.CharField(choices=[('Push', 'Pushing'), ('Pull', 'Pulling'), ('Legs', 'Legs'), ('Core', 'Core')], max_length=20),
        ),
    ]
