# Generated by Django 6.0.2 on 2026-02-19 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muscles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.SmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=2)),
                ('intensity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('muscle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muscles.muscle')),
            ],
        ),
    ]
