# Generated by Django 6.0.2 on 2026-02-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_remove_exercise_difficulty_remove_exercise_intensity_and_more'),
        ('muscles', '0002_alter_muscle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle', to='muscles.muscle'),
        ),
    ]
