# Generated by Django 6.0.2 on 2026-02-19 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_exercises', to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workout')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workout', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reps', models.PositiveIntegerField()),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutexercise')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
    ]
