# Generated by Django 6.0.2 on 2026-02-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercise_muscle'),
        ('workouts', '0002_workout_notes_alter_workout_duration_minutes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutexercise',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout'),
        ),
    ]
